spring.application.name=PCD
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/pcbs_disposal
spring.datasource.username=postgres
spring.datasource.password=postgres